import { Quicksand } from 'next/font/google'
import './global.css';
import 'tailwindcss/tailwind.css';
 
const quicksand = Quicksand({
  subsets: ['latin'],
})


export const metadata = {
  title: "Review Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={quicksand.className}>{children}</body>
    </html>
  );
}
